"use client";

import { useState } from "react";
import { QuoteAnalysis } from "@/types";
import { Download, ChevronDown, FileJson, FileSpreadsheet, FileText } from "lucide-react";

interface DownloadButtonProps {
  analysis: QuoteAnalysis;
}

export default function DownloadButton({ analysis }: DownloadButtonProps) {
  const [isOpen, setIsOpen] = useState(false);

  const downloadJSON = () => {
    const blob = new Blob([JSON.stringify(analysis, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `quote-analysis-${new Date().toISOString().split("T")[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  const downloadCSV = () => {
    const headers = ["Rank", "Vendor", "Base Price", "True Total", "Score", "Pros", "Cons"];
    const rows = analysis.ranking.map((quote, index) => [
      index + 1,
      quote.vendor,
      quote.base_price,
      quote.true_total,
      quote.score,
      `"${quote.pros.join("; ")}"`,
      `"${quote.cons.join("; ")}"`,
    ]);

    const csvContent = [headers.join(","), ...rows.map((row) => row.join(","))].join("\n");
    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `quote-rankings-${new Date().toISOString().split("T")[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  const generateReport = () => {
    const report = `
QUOTE ANALYSIS REPORT
Generated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

================================================================================
RECOMMENDATION
================================================================================
${analysis.recommendation}

Confidence: ${Math.round(analysis.confidence * 100)}%

================================================================================
RANKINGS
================================================================================
${analysis.ranking
  .map(
    (quote, index) => `
#${index + 1} - ${quote.vendor}
   Base Price: $${quote.base_price.toLocaleString()}
   True Total: $${quote.true_total.toLocaleString()}
   Score: ${quote.score}/100

   Pros:
   ${quote.pros.map((p) => `   + ${p}`).join("\n")}

   Cons:
   ${quote.cons.map((c) => `   - ${c}`).join("\n")}
`
  )
  .join("\n")}

${
  analysis.hidden_costs.length > 0
    ? `================================================================================
HIDDEN COSTS DETECTED
================================================================================
${analysis.hidden_costs
  .map(
    (cost) => `
• ${cost.vendor}: ${cost.item}
  Estimated: $${cost.estimated_amount.toLocaleString()}
  Reason: ${cost.reason}
`
  )
  .join("\n")}`
    : ""
}

================================================================================
ANALYSIS REASONING
================================================================================
${analysis.reasoning}

================================================================================
CAVEATS
================================================================================
${analysis.caveats.map((c) => `• ${c}`).join("\n")}

================================================================================
CRITERIA USED
================================================================================
Priorities: ${analysis.criteria_used.priorities.join(" > ")}
${analysis.criteria_used.budget_limit ? `Budget Limit: $${analysis.criteria_used.budget_limit.toLocaleString()}` : ""}
${analysis.criteria_used.must_include ? `Must Include: ${analysis.criteria_used.must_include.join(", ")}` : ""}
${analysis.criteria_used.notes ? `Notes: ${analysis.criteria_used.notes}` : ""}

---
Report generated by WhichBid AI
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `quote-analysis-report-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center space-x-2 px-6 py-3 bg-yellow-500 text-white font-semibold rounded-none hover:bg-yellow-500 transition-all duration-300 transform hover:scale-105 active:scale-95 btn-glow"
      >
        <Download className="w-5 h-5" />
        <span>Download Results</span>
        <ChevronDown
          className={`w-4 h-4 transition-transform duration-300 ${isOpen ? "rotate-180" : ""}`}
        />
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setIsOpen(false)} />
          <div className="absolute right-0 mt-2 w-56 glass rounded-none py-2 z-20 animate-fade-in border border-border">
            <button
              onClick={downloadJSON}
              className="w-full px-4 py-3 text-left hover:bg-card/50 flex items-center space-x-3 transition-all duration-200"
            >
              <div className="w-10 h-10 bg-blue-500 rounded-none flex items-center justify-center">
                <FileJson className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium text-foreground">JSON</p>
                <p className="text-xs text-muted-foreground">Full analysis data</p>
              </div>
            </button>

            <button
              onClick={downloadCSV}
              className="w-full px-4 py-3 text-left hover:bg-card/50 flex items-center space-x-3 transition-all duration-200"
            >
              <div className="w-10 h-10 bg-blue-500 rounded-none flex items-center justify-center">
                <FileSpreadsheet className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium text-foreground">CSV</p>
                <p className="text-xs text-muted-foreground">Rankings for Excel</p>
              </div>
            </button>

            <button
              onClick={generateReport}
              className="w-full px-4 py-3 text-left hover:bg-card/50 flex items-center space-x-3 transition-all duration-200"
            >
              <div className="w-10 h-10 bg-yellow-500 rounded-none flex items-center justify-center">
                <FileText className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="font-medium text-foreground">Report</p>
                <p className="text-xs text-muted-foreground">Formatted text report</p>
              </div>
            </button>
          </div>
        </>
      )}
    </div>
  );
}
