"use client";

import { useState } from "react";
import { Share2, Check, Copy } from "lucide-react";
import { QuoteAnalysis } from "@/types";

interface ShareButtonProps {
    analysis: QuoteAnalysis;
}

export default function ShareButton({ analysis }: ShareButtonProps) {
    const [copied, setCopied] = useState(false);

    const generateSummary = (): string => {
        const { ranking, recommendation, hidden_costs, confidence } = analysis;
        const topVendor = ranking[0];
        const prices = ranking.map((q) => q.true_total);
        const savings = Math.max(...prices) - Math.min(...prices);

        const summary = `
📊 WhichBid Quote Analysis Summary
${"═".repeat(40)}

🏆 RECOMMENDED: ${topVendor.vendor}
   Score: ${topVendor.score}/100 | Total: $${topVendor.true_total.toLocaleString()}

📈 COMPARISON (${ranking.length} quotes analyzed):
${ranking.map((q, i) => `   ${i + 1}. ${q.vendor}: $${q.true_total.toLocaleString()} (Score: ${q.score})`).join("\n")}

💰 POTENTIAL SAVINGS: $${savings.toLocaleString()}
⚠️ HIDDEN COSTS FOUND: ${hidden_costs.length}
🎯 AI CONFIDENCE: ${Math.round(confidence * 100)}%

💡 RECOMMENDATION:
${recommendation}

${"─".repeat(40)}
Generated by WhichBid AI • ${new Date().toLocaleDateString()}
    `.trim();

        return summary;
    };

    const handleShare = async () => {
        const summary = generateSummary();

        // Try native share API first (mobile)
        if (navigator.share) {
            try {
                await navigator.share({
                    title: "WhichBid Quote Analysis",
                    text: summary,
                });
                return;
            } catch {
                // Fall through to clipboard
            }
        }

        // Copy to clipboard
        try {
            await navigator.clipboard.writeText(summary);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch {
            // Fallback for older browsers
            const textarea = document.createElement("textarea");
            textarea.value = summary;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand("copy");
            document.body.removeChild(textarea);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    return (
        <button
            onClick={handleShare}
            className={`
        flex items-center space-x-2 px-4 py-2 rounded-lg font-medium text-sm
        transition-all duration-300 shadow-lg
        ${copied
                    ? "bg-green-500 text-white"
                    : "bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white hover:shadow-xl hover:scale-105"
                }
      `}
            title="Copy analysis summary to clipboard"
        >
            {copied ? (
                <>
                    <Check className="w-4 h-4" />
                    <span>Copied!</span>
                </>
            ) : (
                <>
                    <Share2 className="w-4 h-4" />
                    <span className="hidden sm:inline">Share Summary</span>
                    <span className="sm:hidden">Share</span>
                </>
            )}
        </button>
    );
}
